---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: python
    tag: 3.10

inputs:
- name: dp-nlp-berlin-api

outputs:
- name: build

run:
  path: dp-nlp-berlin-api/ci/scripts/build.sh